### PR TITLE
args as interface

### PR DESCRIPTION
**Pull request by PhakornKiong**
Alternative interface as discussed
https://github.com/pavebank/pdk-go/blob/pdk-combine-args/pdk.go

```go
// TriggerInput represents API contract for Trigger-Handler
// ActionInput and ActionOutput represents API contract for Actions
// All these contract should be made available via our paveapps SDK
type TriggerInput struct {
	Message string
}

type ActionInput struct {
	Input string
	Num   int
}

type ActionOutput struct {
	Output string
	Num    int
}

//export actionLog
func actionLog(x paveapps.Args)

//export actionDoubleInt
func actionDoubleInt(x paveapps.Args) paveapps.Args

//export afterSomething
func afterSomething() {
	// Creating an input to call action
	in := ActionInput{
		Input: "this is input",
		Num:   250,
	}

	offsetInput, err := paveapps.ToArgs(in)

	if err != nil {
		// There are always an error for ToArgs, so how should we handle simple []byte
		errorString, err := paveapps.ToArgs([]byte("error string here for example"))
		actionLog(errorString)
		return
}

func main() {}
```

### CODE REVIEW

**Comment by LukaGiorgadze** [comment]
Let's merge this after Simon finishes demoing.

**Comment by PhakornKiong** [comment]
> Let's merge this after Simon finishes demoing. Thoughts?

@LukaGiorgadze If you agree with this structure, lets merge it then. Else, you can look at the alternative branch, which is more aligned to what you've proposed previously.

**Comment by LukaGiorgadze** [comment]
@PhakornKiong I thought the code example from the description was from this PR.
Then I think the [alternative](https://github.com/pavebank/pdk-go/blob/pdk-combine-args/pdk.go) approach is easier and developer friendly as we discussed before for sure.

**Review by LukaGiorgadze — APPROVED** [review]
@PhakornKiong 
Okay, here is my thoughts:
Because of we use marshaling under the hood, that's why we are forced to return errs every time.
I think this PR makes more sense, so `BytesToArgs` is something that usually people will use but we will provide bytesToStruct as a helper to not write `unmarshall` manually.

Also, one more thing, since our default communication type is a `byte` (which makes sense), maybe split the input into two parts? So instead of `Input` let's split this as well, because what if I want input as a byte? I should use struct and then convert it into bytes again(?).

so it would be nice if we will have:

`InputByte` and `InputStruct` (not sure if it's a best name, maybe you suggest better?)

**Comment by PhakornKiong** [comment]
@LukaGiorgadze I think that `Input` to the `trigger handler` will be fixed to being `json` that get unmarshal to a `struct`. Not sure whats the case where we will pass in `byte` thats not a `json`.

Lets work on the documentation separately, since we will need to first figure out how do we expose the `api contract` for all the `trigger handler` and `actions` in our `pdk`. User still have to re-declare those struct manually.

**Review by LukaGiorgadze — APPROVED** [review]

**Pull request merged**
